# Generated by Django 6.0.4 on 2026-05-14 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companymembership_sitemembership'),
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type_code', models.CharField(max_length=80)),
                ('region_code', models.CharField(default='CL', max_length=20)),
                ('um_code', models.CharField(max_length=20)),
                ('industry_hh_per_unit', models.DecimalField(decimal_places=4, max_digits=10)),
                ('source_notes', models.TextField(blank=True, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benchmarks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benchmark de industria',
                'verbose_name_plural': 'Benchmarks de industria',
                'db_table': 'analytics_industry_benchmark',
                'ordering': ['task_type_code', 'region_code'],
            },
        ),
        migrations.CreateModel(
            name='TaskBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('um_code', models.CharField(max_length=20)),
                ('budget_hh_per_unit', models.DecimalField(decimal_places=4, max_digits=10)),
                ('budget_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('budget_hh_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_budgets_created', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_budgets', to='companies.site')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='work.taskcatalog')),
            ],
            options={
                'verbose_name': 'Presupuesto de partida',
                'verbose_name_plural': 'Presupuestos de partida',
                'db_table': 'analytics_task_budget',
                'ordering': ['site', 'task'],
            },
        ),
        migrations.CreateModel(
            name='TaskApuMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apu_code', models.CharField(max_length=120)),
                ('apu_description', models.CharField(max_length=255)),
                ('weight_factor', models.DecimalField(decimal_places=4, default=1.0, max_digits=6)),
                ('task_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apu_mappings', to='analytics.taskbudget')),
            ],
            options={
                'verbose_name': 'Mapeo APU',
                'verbose_name_plural': 'Mapeos APU',
                'db_table': 'analytics_task_apu_mapping',
            },
        ),
        migrations.CreateModel(
            name='WeeklySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_number', models.IntegerField()),
                ('hh_real', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hh_productive', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hh_disponibles_jornada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('icc_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('avg_start_time', models.TimeField(blank=True, null=True)),
                ('resource_count', models.IntegerField(default=0)),
                ('physical_progress_week', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('physical_progress_acum', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('um_code', models.CharField(blank=True, max_length=20, null=True)),
                ('rendimiento_real_hh_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rendimiento_presupuesto', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rendimiento_industria', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('prod_real_acum', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('prod_teorica_presup', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('is_partial', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_snapshots', to='companies.site')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_snapshots', to='work.stage')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_snapshots', to='work.taskcatalog')),
            ],
            options={
                'verbose_name': 'Snapshot semanal',
                'verbose_name_plural': 'Snapshots semanales',
                'db_table': 'analytics_weekly_snapshot',
                'ordering': ['-week_start', 'stage', 'task'],
                'constraints': [models.UniqueConstraint(fields=('site', 'stage', 'task', 'week_start'), name='unique_weekly_snapshot')],
            },
        ),
    ]
