# Generated by Django 6.0.4 on 2026-07-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('companies', '0005_siteworkdayconfig_autoclose_and_vigencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductivitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trab', models.IntegerField(default=0, help_text='Trabajadores unicos con sesion ese dia')),
                ('hh', models.DecimalField(decimal_places=2, default=0, help_text='HH asignadas, ya ajustadas por descuento de colacion', max_digits=10)),
                ('costo_hh', models.IntegerField(default=0, help_text='Costo en pesos de las HH asignadas')),
                ('hh_pag', models.DecimalField(decimal_places=2, default=0, help_text='HH pagadas: jornada (SiteWorkdayConfig) x trabajadores', max_digits=10)),
                ('icc', models.DecimalField(decimal_places=4, default=0, help_text='Indice de cumplimiento: hh / hh_pag', max_digits=6)),
                ('avg_start_time', models.TimeField(blank=True, help_text='Hora promedio de inicio de jornada', null=True)),
                ('hm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_hm', models.IntegerField(default=0)),
                ('maq', models.IntegerField(default=0, help_text='Maquinas activas ese dia')),
                ('etapas_hh', models.JSONField(default=list, help_text='[{"e": etapa, "HH": num, "c": costo}, ...]')),
                ('etapas_hm', models.JSONField(default=list, help_text='[{"e": etapa, "HM": num, "c": costo}, ...]')),
                ('sups', models.JSONField(default=list, help_text='[{"n": nombre, "HH": num, "c": costo, "t": trabajadores}, ...]')),
                ('cargos', models.JSONField(default=list, help_text='[{"n": cargo, "HH": num, "c": costo}, ...]')),
                ('partidas', models.JSONField(default=list, help_text='Top partidas por HH: [{"p": partida, "e": etapa, "HH": num}, ...]')),
                ('maquinas', models.JSONField(default=list, help_text='[{"n": nombre, "tipo": cargo, "HM": num, "c": costo}, ...]')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_productivity_snapshots', to='companies.site')),
            ],
            options={
                'verbose_name': 'Snapshot diario de productividad',
                'verbose_name_plural': 'Snapshots diarios de productividad',
                'db_table': 'analytics_daily_productivity_snapshot',
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyproductivitysnapshot',
            constraint=models.UniqueConstraint(fields=('site', 'date'), name='unique_daily_productivity_snapshot'),
        ),
    ]
