# Generated by Django 6.0.4 on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_dailyproductivitysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproductivitysnapshot',
            name='costo_pag',
            field=models.IntegerField(
                default=0,
                help_text='Costo en pesos de la jornada completa pagada (a la tasa de cada trabajador)',
            ),
        ),
    ]
