# Generated by Django 6.0.4 on 2026-04-29 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companymembership_sitemembership'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MassCloseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_count', models.IntegerField(default=0)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mass_close_batches', to='companies.company')),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mass_close_batches', to=settings.AUTH_USER_MODEL)),
                ('responsible_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mass_close_batches_supervised', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mass_close_batches', to='companies.site')),
            ],
            options={
                'verbose_name': 'Lote de cierre masivo',
                'verbose_name_plural': 'Lotes de cierre masivo',
                'db_table': 'work_mass_close_batch',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=40)),
                ('stage_type', models.CharField(choices=[('NORMAL', 'Normal'), ('REPROCESS', 'Reproceso'), ('RESERVED', 'Reservada'), ('SUBCONTRACT_RESERVED', 'Reservada subcontrato')], default='NORMAL', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_reserved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='companies.company')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='companies.site')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'db_table': 'work_stage',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorStagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_permissions', to='companies.sitemembership')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_permissions', to='work.stage')),
            ],
            options={
                'verbose_name': 'Permiso de etapa por supervisor',
                'verbose_name_plural': 'Permisos de etapa por supervisor',
                'db_table': 'work_supervisor_stage_permission',
            },
        ),
        migrations.CreateModel(
            name='TaskCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH_RISK', 'Alto riesgo')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('INACTIVE', 'Inactiva')], default='ACTIVE', max_length=20)),
                ('default_um', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_catalog', to='companies.company')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'db_table': 'work_task_catalog',
                'ordering': ['company', 'code'],
            },
        ),
        migrations.CreateModel(
            name='StageTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_tasks', to='companies.site')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_tasks', to='work.stage')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_tasks', to='work.taskcatalog')),
            ],
            options={
                'verbose_name': 'Partida de etapa',
                'verbose_name_plural': 'Partidas de etapa',
                'db_table': 'work_stage_task',
                'ordering': ['stage', 'display_order', 'task'],
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name_snapshot', models.CharField(max_length=120)),
                ('task_code_snapshot', models.CharField(max_length=60)),
                ('task_name_snapshot', models.CharField(max_length=180)),
                ('risk_level_snapshot', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('duration_productive_minutes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada'), ('AUTO_CLOSED', 'Cierre automatico'), ('VOIDED', 'Anulada')], default='OPEN', max_length=20)),
                ('operated_by_role_code', models.CharField(blank=True, max_length=80, null=True)),
                ('is_overtime', models.BooleanField(default=False)),
                ('closure_origin', models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('MASS_CLOSE', 'Cierre masivo'), ('AUTO_CLOSE', 'Cierre automatico'), ('OVERTIME_SPLIT', 'Division hora extra')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='companies.company')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_ended', to=settings.AUTH_USER_MODEL)),
                ('parent_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_sessions', to='work.worksession')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='resources.resource')),
                ('resource_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='resources.resourcesiteassignment')),
                ('responsible_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_supervised', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='companies.site')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='work.stage')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_started', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='work.taskcatalog')),
            ],
            options={
                'verbose_name': 'Sesion de trabajo',
                'verbose_name_plural': 'Sesiones de trabajo',
                'db_table': 'work_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MassCloseBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_at_effective', models.DateTimeField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='work.massclosebatch')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mass_close_items', to='work.worksession')),
            ],
            options={
                'verbose_name': 'Item de cierre masivo',
                'verbose_name_plural': 'Items de cierre masivo',
                'db_table': 'work_mass_close_batch_item',
            },
        ),
        migrations.CreateModel(
            name='WorkSessionChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('DAY_CORRECTION', 'Correccion del dia'), ('FORCE_CLOSE', 'Cierre forzado'), ('OVERTIME_SPLIT', 'Division hora extra'), ('VOID', 'Anulacion')], max_length=20)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_changes', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='work.worksession')),
            ],
            options={
                'verbose_name': 'Log de cambio de sesion',
                'verbose_name_plural': 'Logs de cambio de sesion',
                'db_table': 'work_session_change_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OvertimePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.SmallIntegerField()),
                ('normal_end_time', models.TimeField(blank=True, null=True)),
                ('all_day_overtime', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_policies', to='companies.site')),
            ],
            options={
                'verbose_name': 'Politica de hora extra',
                'verbose_name_plural': 'Politicas de hora extra',
                'db_table': 'work_overtime_policy',
                'constraints': [models.UniqueConstraint(fields=('site', 'weekday'), name='unique_overtime_policy_per_site_weekday')],
            },
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(fields=('company', 'site', 'name'), name='unique_stage_name_per_company_site'),
        ),
        migrations.AddConstraint(
            model_name='supervisorstagepermission',
            constraint=models.UniqueConstraint(fields=('site_membership', 'stage'), name='unique_supervisor_stage_permission'),
        ),
        migrations.AddConstraint(
            model_name='taskcatalog',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_task_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='stagetask',
            constraint=models.UniqueConstraint(fields=('site', 'stage', 'task'), name='unique_stage_task_per_site'),
        ),
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('resource',), name='unique_open_session_per_resource'),
        ),
        migrations.AddConstraint(
            model_name='massclosebatchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'session'), name='unique_batch_session'),
        ),
    ]
