# Generated by Django 6.0.4 on 2026-06-02 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_redesign_stage_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtimepolicy',
            options={'verbose_name': 'Politica de jornada', 'verbose_name_plural': 'Politicas de jornada'},
        ),
        migrations.AlterField(
            model_name='overtimepolicy',
            name='all_day_overtime',
            field=models.BooleanField(default=False, help_text='Si esta marcado, todo el dia se considera hora extra y no hay cierre automatico.'),
        ),
        migrations.AlterField(
            model_name='overtimepolicy',
            name='auto_close_time',
            field=models.TimeField(blank=True, help_text='Hora en que el sistema cierra sesiones abiertas. Debe ser posterior a normal_end_time (buffer recomendado: 1-2 hrs).', null=True),
        ),
        migrations.AlterField(
            model_name='overtimepolicy',
            name='normal_end_time',
            field=models.TimeField(blank=True, help_text='Hora oficial de fin de jornada. Se escribe en ended_at al cerrar automaticamente.', null=True),
        ),
        migrations.AlterField(
            model_name='overtimepolicy',
            name='weekday',
            field=models.SmallIntegerField(help_text='0=Lunes, 1=Martes, 2=Miercoles, 3=Jueves, 4=Viernes, 5=Sabado, 6=Domingo'),
        ),
        migrations.AlterField(
            model_name='supervisortaskpermission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
