# Generated by Django 6.0.4 on 2026-06-02 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_overtimepolicy_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksessionchangelog',
            name='change_type',
            field=models.CharField(choices=[('DAY_CORRECTION', 'Correccion del dia'), ('FORCE_CLOSE', 'Cierre forzado'), ('OVERTIME_SPLIT', 'Division hora extra'), ('VOID', 'Anulacion'), ('AUTO_CLOSE', 'Cierre automatico')], max_length=20),
        ),
        migrations.AlterField(
            model_name='worksessionchangelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_changes', to=settings.AUTH_USER_MODEL),
        ),
    ]
