# Generated by Django 6.0.4 on 2026-06-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_add_holidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chilepublicholiday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chilepublicholiday',
            name='is_recurring',
            field=models.BooleanField(default=True, help_text='True = feriado fijo que se repite cada año. False = variable (Semana Santa, etc.)'),
        ),
        migrations.AlterField(
            model_name='siteholiday',
            name='description',
            field=models.CharField(help_text='Ej: Viernes sandwich feriado 18 de septiembre', max_length=180),
        ),
        migrations.AlterField(
            model_name='siteholiday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
