# Generated by Django 6.0.4 on 2026-07-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_stagetask_presupuesto_total'),
        ('companies', '0005_siteworkdayconfig_autoclose_and_vigencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OvertimePolicy',
        ),
    ]
