# Generated by Django 6.0.4 on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_delete_overtimepolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='closure_origin',
            field=models.CharField(
                blank=True,
                choices=[
                    ('MANUAL', 'Manual'),
                    ('MASS_CLOSE', 'Cierre masivo'),
                    ('TASK_CLOSE', 'Cierre por partida'),
                    ('AUTO_CLOSE', 'Cierre automatico'),
                    ('OVERTIME_SPLIT', 'Division hora extra'),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
