# Generated by Django 6.0.4 on 2026-07-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_worksession_closure_origin_task_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagetask',
            name='cantidad_presupuesto',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad presupuestada en unidad de medida de la partida', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='stagetask',
            name='partida_cod',
            field=models.CharField(blank=True, help_text='Concatenacion subetapa|partida para compatibilidad con Excel RRA', max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='stagetask',
            name='presupuesto_mo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto de mano obra directa en pesos', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='stagetask',
            name='subetapa',
            field=models.CharField(blank=True, help_text='Nombre de la subetapa. Ej: 1.2.3.3. ARMADURAS DE ACERO', max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='stagetask',
            name='tipo',
            field=models.CharField(choices=[('casa', 'Casa'), ('subcontrato', 'Subcontrato')], default='casa', help_text='Casa = MOD propia. Subcontrato = mano de obra tercerizada.', max_length=20),
        ),
        migrations.AlterField(
            model_name='stagetask',
            name='unidad_medida',
            field=models.CharField(blank=True, help_text='Unidad de medida. Ej: m2, ml, un', max_length=20, null=True),
        ),
    ]
