# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_alter_stagetask_cantidad_presupuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='needs_review',
            field=models.BooleanField(
                default=False,
                help_text='Cierre manual/masivo/por partida cuya hora real se aleja del '
                          'work_end_time oficial mas alla de settings.REVIEW_CLOSE_THRESHOLD_MINUTES. '
                          'No bloquea nada — es solo para la bandeja de revision del prestador.',
            ),
        ),
        migrations.AlterField(
            model_name='worksessionchangelog',
            name='change_type',
            field=models.CharField(
                choices=[
                    ('DAY_CORRECTION', 'Correccion del dia'),
                    ('FORCE_CLOSE', 'Cierre forzado'),
                    ('OVERTIME_SPLIT', 'Division hora extra'),
                    ('VOID', 'Anulacion'),
                    ('AUTO_CLOSE', 'Cierre automatico'),
                    ('PROVIDER_ADJUST', 'Ajuste del prestador (bandeja de revision)'),
                ],
                max_length=20,
            ),
        ),
    ]
