# Generated by Django 6.0.4 on 2026-05-14 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companymembership_sitemembership'),
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProgressFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('file_type', models.CharField(choices=[('XLSX', 'Excel'), ('CSV', 'CSV')], default='XLSX', max_length=10)),
                ('sheet_name_rule', models.CharField(blank=True, max_length=120, null=True)),
                ('header_row', models.IntegerField(blank=True, null=True)),
                ('start_row', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_formats', to='companies.company')),
            ],
            options={
                'verbose_name': 'Formato de avance',
                'verbose_name_plural': 'Formatos de avance',
                'db_table': 'planning_company_progress_format',
            },
        ),
        migrations.CreateModel(
            name='ProgressBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('XLSX', 'Excel'), ('CSV', 'CSV')], default='MANUAL', max_length=20)),
                ('week_start', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('APPLIED', 'Aplicado'), ('VOIDED', 'Anulado')], default='DRAFT', max_length=20)),
                ('source_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_batches', to='companies.company')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_batches', to='companies.site')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carga de avance',
                'verbose_name_plural': 'Cargas de avance',
                'db_table': 'planning_progress_batch',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('um_code', models.CharField(max_length=20)),
                ('progress_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='planning.progressbatch')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_entries', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_entries', to='companies.site')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_entries', to='work.stage')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_entries', to='work.taskcatalog')),
            ],
            options={
                'verbose_name': 'Entrada de avance',
                'verbose_name_plural': 'Entradas de avance',
                'db_table': 'planning_progress_entry',
                'ordering': ['-week_start', 'stage', 'task'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProgressMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_field', models.CharField(max_length=80)),
                ('source_column', models.CharField(max_length=20)),
                ('transform_rule', models.CharField(blank=True, max_length=120, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='planning.companyprogressformat')),
            ],
            options={
                'verbose_name': 'Mapeo de formato de avance',
                'verbose_name_plural': 'Mapeos de formato de avance',
                'db_table': 'planning_company_progress_mapping',
                'constraints': [models.UniqueConstraint(fields=('format', 'logical_field'), name='unique_mapping_per_format')],
            },
        ),
    ]
