# Generated by Django 6.0.4 on 2026-04-28 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('INACTIVE', 'Inactiva'), ('ARCHIVED', 'Archivada')], default='ACTIVE', max_length=20)),
                ('tax_id', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'companies_company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_mode', models.CharField(choices=[('PERSONAS', 'Solo personas'), ('MAQUINARIAS', 'Solo maquinarias'), ('MIXTA', 'Mixta')], default='PERSONAS', max_length=20)),
                ('allow_people', models.BooleanField(default=True)),
                ('allow_machinery', models.BooleanField(default=False)),
                ('allow_subcontracts', models.BooleanField(default=True)),
                ('allow_orgchart', models.BooleanField(default=False)),
                ('allow_planning', models.BooleanField(default=False)),
                ('allow_assistance', models.BooleanField(default=False)),
                ('allow_payroll', models.BooleanField(default=False)),
                ('allow_google_sheet_export', models.BooleanField(default=False)),
                ('allow_internal_dashboard', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='companies.company')),
            ],
            options={
                'verbose_name': 'Configuracion de empresa',
                'verbose_name_plural': 'Configuraciones de empresa',
                'db_table': 'companies_company_config',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('PLANNED', 'Planificada'), ('ACTIVE', 'Activa'), ('PAUSED', 'Pausada'), ('CLOSED', 'Cerrada'), ('ARCHIVED', 'Archivada')], default='PLANNED', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('timezone', models.CharField(default='America/Santiago', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='companies.company')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'db_table': 'companies_site',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_people', models.BooleanField(default=True)),
                ('use_machinery', models.BooleanField(default=False)),
                ('use_subcontracts', models.BooleanField(default=True)),
                ('use_orgchart', models.BooleanField(default=False)),
                ('use_planning', models.BooleanField(default=False)),
                ('use_assistance', models.BooleanField(default=False)),
                ('use_internal_dashboard', models.BooleanField(default=False)),
                ('show_supervisor_dashboard', models.BooleanField(default=False)),
                ('show_admin_dashboard', models.BooleanField(default=False)),
                ('show_aac_dashboard', models.BooleanField(default=False)),
                ('enable_no_on_site_tracking', models.BooleanField(default=True)),
                ('enable_no_on_site_alert_only', models.BooleanField(default=True)),
                ('high_risk_email_batch_minutes', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='companies.site')),
            ],
            options={
                'verbose_name': 'Configuracion de obra',
                'verbose_name_plural': 'Configuraciones de obra',
                'db_table': 'companies_site_config',
            },
        ),
        migrations.CreateModel(
            name='SiteWorkdayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')])),
                ('work_start_time', models.TimeField()),
                ('work_end_time', models.TimeField()),
                ('lunch_start_time', models.TimeField(blank=True, null=True)),
                ('lunch_end_time', models.TimeField(blank=True, null=True)),
                ('deduct_lunch_from_icc', models.BooleanField(default=True)),
                ('all_day_overtime', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workday_configs', to='companies.site')),
            ],
            options={
                'verbose_name': 'Configuracion de jornada',
                'verbose_name_plural': 'Configuraciones de jornada',
                'db_table': 'companies_site_workday_config',
            },
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_site_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='siteworkdayconfig',
            constraint=models.UniqueConstraint(fields=('site', 'weekday'), name='unique_workday_per_site'),
        ),
    ]
