# Generated by Django 6.0.4 on 2026-06-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_site_week_cargo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitecargovalor',
            options={'ordering': ['site', 'cargo'], 'verbose_name': 'Valor HH por cargo', 'verbose_name_plural': 'Valores HH por cargo'},
        ),
        migrations.AlterModelOptions(
            name='siteweekconfig',
            options={'verbose_name': 'Configuracion de semanas ISA', 'verbose_name_plural': 'Configuraciones de semanas ISA'},
        ),
        migrations.AlterField(
            model_name='sitecargovalor',
            name='cargo',
            field=models.CharField(help_text='Nombre del cargo exactamente como aparece en las sesiones', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitecargovalor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitecargovalor',
            name='valor_hh',
            field=models.DecimalField(decimal_places=2, help_text='Valor en pesos por hora hombre', max_digits=10),
        ),
        migrations.AlterField(
            model_name='siteweekconfig',
            name='base_monday',
            field=models.DateField(help_text='Lunes de la semana base. Ej: 04-05-2026'),
        ),
        migrations.AlterField(
            model_name='siteweekconfig',
            name='base_week',
            field=models.PositiveIntegerField(help_text='Numero de semana ISA que corresponde a ese lunes. Ej: 20'),
        ),
        migrations.AlterField(
            model_name='siteweekconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='siteweekconfig',
            name='prefix',
            field=models.CharField(default='sem ', help_text='Prefijo para el nombre de semana. Default: "sem "', max_length=20),
        ),
    ]
