# Generated by Django 6.0.4 on 2026-07-07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_sitecargovalor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteworkdayconfig',
            options={
                'ordering': ['site', 'weekday', '-effective_from'],
                'verbose_name': 'Configuracion de jornada',
                'verbose_name_plural': 'Configuraciones de jornada',
            },
        ),
        migrations.RemoveConstraint(
            model_name='siteworkdayconfig',
            name='unique_workday_per_site',
        ),
        migrations.AddField(
            model_name='siteworkdayconfig',
            name='auto_close_time',
            field=models.TimeField(
                blank=True, null=True,
                help_text='Hora en que Celery cierra sesiones abiertas automaticamente. '
                          'Debe ser posterior a work_end_time (buffer recomendado: 1-2 hrs). '
                          'Si se deja vacio, esta jornada no tiene cierre automatico.',
            ),
        ),
        migrations.AddField(
            model_name='siteworkdayconfig',
            name='effective_from',
            field=models.DateField(
                default=datetime.date(2020, 1, 1),
                help_text='Desde cuando aplica esta configuracion de jornada.',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteworkdayconfig',
            name='effective_to',
            field=models.DateField(
                blank=True, null=True,
                help_text='Hasta cuando aplica. Vacio = vigente indefinidamente.',
            ),
        ),
        migrations.AlterField(
            model_name='siteworkdayconfig',
            name='work_end_time',
            field=models.TimeField(
                help_text='Hora oficial de fin de jornada. Define las HH pagadas del dia '
                          'y se escribe como ended_at en los cierres automaticos.',
            ),
        ),
        migrations.AlterField(
            model_name='siteworkdayconfig',
            name='all_day_overtime',
            field=models.BooleanField(
                default=False,
                help_text='Si esta marcado, todo el dia se considera hora extra y no hay cierre automatico.',
            ),
        ),
        migrations.AddConstraint(
            model_name='siteworkdayconfig',
            constraint=models.UniqueConstraint(
                fields=('site', 'weekday', 'effective_from'),
                name='unique_workday_per_site_effective_from',
            ),
        ),
    ]
