# Generated by Django 6.0.4

from django.db import migrations


class Migration(migrations.Migration):
    """
    Saca auto_close_time de SiteWorkdayConfig. El cierre automatico de
    sesiones dejo de ser por-obra: ahora es un job nocturno global (una
    sola hora para todo el sistema, ver settings.AUTO_CLOSE_SESSIONS_HOUR
    y CELERY_BEAT_SCHEDULE), asi que el campo ya no tiene uso.
    """

    dependencies = [
        ('companies', '0006_companymembership_management_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteworkdayconfig',
            name='auto_close_time',
        ),
    ]
