# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_siteworkdayconfig_auto_close_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteworkdayconfig',
            name='work_start_time',
            field=models.TimeField(
                blank=True, null=True,
                help_text='Vacio solo si is_active=False (dia marcado explicitamente '
                          'como no laborable).',
            ),
        ),
        migrations.AlterField(
            model_name='siteworkdayconfig',
            name='work_end_time',
            field=models.TimeField(
                blank=True, null=True,
                help_text='Hora oficial de fin de jornada. Define las HH pagadas del dia '
                          'y se escribe como ended_at en los cierres automaticos. '
                          'Vacio solo si is_active=False.',
            ),
        ),
    ]
