# Generated by Django 6.0.4 on 2026-05-14 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companymembership_sitemembership'),
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcontract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontracts', to='companies.company')),
                ('reserved_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontracts', to='work.stage')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontracts', to='companies.site')),
            ],
            options={
                'verbose_name': 'Subcontrato',
                'verbose_name_plural': 'Subcontratos',
                'db_table': 'subcontracts_subcontract',
                'ordering': ['site', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubcontractSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('PARTIAL', 'Parcial'), ('CLOSED', 'Cerrada'), ('VOIDED', 'Anulada')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontract_sessions', to='companies.company')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontract_sessions_ended', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontract_sessions', to='companies.site')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontract_sessions', to='work.stage')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontract_sessions_started', to=settings.AUTH_USER_MODEL)),
                ('subcontract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='subcontracts.subcontract')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontract_sessions', to='work.taskcatalog')),
            ],
            options={
                'verbose_name': 'Sesion de subcontrato',
                'verbose_name_plural': 'Sesiones de subcontrato',
                'db_table': 'subcontracts_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SubcontractSessionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_started', models.DecimalField(decimal_places=4, max_digits=14)),
                ('quantity_closed', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unit_code', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='subcontracts.subcontractsession')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontract_details_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle de sesion de subcontrato',
                'verbose_name_plural': 'Detalles de sesion de subcontrato',
                'db_table': 'subcontracts_session_detail',
            },
        ),
        migrations.CreateModel(
            name='SubcontractSessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('DAY_EDIT', 'Edicion del dia'), ('QUANTITY_ADJUSTMENT', 'Ajuste de cantidad'), ('FORCE_CLOSE', 'Cierre forzado')], max_length=30)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontract_history', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='subcontracts.subcontractsession')),
            ],
            options={
                'verbose_name': 'Historial de sesion de subcontrato',
                'verbose_name_plural': 'Historiales de sesion de subcontrato',
                'db_table': 'subcontracts_session_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='subcontract',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='unique_subcontract_code_per_site'),
        ),
    ]
