# Generated by Django 6.0.4 on 2026-05-14 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companymembership_sitemembership'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoOnSiteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('reason_code', models.CharField(choices=[('PERMISO', 'Permiso'), ('LICENCIA', 'Licencia medica'), ('AUSENTE', 'Ausente sin aviso'), ('VACACIONES', 'Vacaciones'), ('OTRO', 'Otro')], default='AUSENTE', max_length=40)),
                ('detail', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('VOIDED', 'Anulado')], default='ACTIVE', max_length=20)),
                ('voided_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='no_on_site_events', to='companies.company')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='no_on_site_events_marked', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='no_on_site_events', to='resources.resource')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='no_on_site_events', to='companies.site')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_on_site_events_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento No en obra',
                'verbose_name_plural': 'Eventos No en obra',
                'db_table': 'tracking_no_on_site_event',
                'ordering': ['-event_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('site', 'resource', 'event_date'), name='unique_active_no_on_site_per_day')],
            },
        ),
    ]
