# Generated by Django 6.0.4 on 2026-04-29 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('OPERACION', 'Operacion'), ('RECURSOS', 'Recursos'), ('SUBCONTRATOS', 'Subcontratos'), ('CONFIGURACION', 'Configuracion'), ('CONFIGURACION_ESTRUCTURAL', 'Configuracion estructural'), ('USUARIOS', 'Usuarios y roles'), ('DASHBOARDS', 'Dashboards y reportes'), ('ASISTENCIA', 'Asistencia y remuneraciones'), ('PLANIFICACION', 'Planificacion y avance'), ('ORGANIGRAMA', 'Organigrama')], max_length=40)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('level', models.CharField(choices=[('VIEW', 'Ver'), ('OPERATE', 'Operar'), ('ADMIN', 'Administrar'), ('SENSITIVE', 'Accion sensible')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'access_permission',
                'ordering': ['module', 'level'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('scope_type', models.CharField(choices=[('GLOBAL_BASE', 'Base global'), ('COMPANY_CUSTOM', 'Custom por empresa')], default='GLOBAL_BASE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'access_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='America/Santiago', max_length=64)),
                ('extra_json', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_active_users', to='companies.company')),
                ('last_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_active_users', to='companies.site')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de usuario',
                'verbose_name_plural': 'Preferencias de usuario',
                'db_table': 'access_user_preference',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='access.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='access.role')),
            ],
            options={
                'verbose_name': 'Permiso de rol',
                'verbose_name_plural': 'Permisos de rol',
                'db_table': 'access_role_permission',
                'constraints': [models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission')],
            },
        ),
    ]
