# Generated by Django 6.0.4 on 2026-06-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_site_membership_permission_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemembershippermissionoverride',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
