# Generated by Django 6.0.4 on 2026-06-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_alter_sitemembershippermissionoverride_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='Rol protegido del sistema (ej: novus_super, novus_consultor). Sus permisos no pueden modificarse desde la UI de gestion de roles.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_novus_super',
            field=models.BooleanField(default=False, help_text='Acceso total al sistema: todas las empresas y obras, sin excepcion. Es independiente de membresias (CompanyMembership/SiteMembership) y se otorga automaticamente en cada empresa/obra nueva via signals. Otorgar solo a personal interno de Novus de maxima confianza.'),
        ),
    ]
