# Generated by Django 6.0.4 on 2026-05-14 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companymembership_sitemembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('SENT', 'Enviado'), ('FAILED', 'Fallido'), ('SKIPPED', 'Omitido')], max_length=20)),
                ('recipients_json', models.JSONField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_logs', to='companies.site')),
            ],
            options={
                'verbose_name': 'Log de alerta',
                'verbose_name_plural': 'Logs de alerta',
                'db_table': 'notifications_alert_log',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteAlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('HIGH_RISK_START', 'Inicio alto riesgo'), ('ACTIVE_WITHOUT_SESSION', 'Activo sin sesion'), ('POST_LUNCH_UNASSIGNED', 'Sin asignar post colacion'), ('OPEN_AFTER_SHIFT', 'Sesion abierta fuera de jornada')], max_length=40)),
                ('is_enabled', models.BooleanField(default=True)),
                ('to_emails', models.JSONField(default=list)),
                ('cc_emails', models.JSONField(blank=True, default=list)),
                ('send_window_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_configs', to='companies.site')),
            ],
            options={
                'verbose_name': 'Configuracion de alerta',
                'verbose_name_plural': 'Configuraciones de alerta',
                'db_table': 'notifications_site_alert_config',
                'constraints': [models.UniqueConstraint(fields=('site', 'alert_type'), name='unique_alert_config_per_site')],
            },
        ),
    ]
