# Generated by Django 6.0.4

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('companies', '0007_remove_siteworkdayconfig_auto_close_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUnassignedAlertSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.TimeField(help_text='Hora local de la obra en que se revisa si hay activos sin partida.')),
                ('to_emails', models.JSONField(default=list, help_text='Lista de correos TO.')),
                ('cc_emails', models.JSONField(blank=True, default=list, help_text='Lista de correos CC (opcional).')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unassigned_alert_schedules', to='companies.site')),
            ],
            options={
                'verbose_name': 'Horario de alerta — activos sin partida',
                'verbose_name_plural': 'Horarios de alerta — activos sin partida',
                'db_table': 'notifications_site_unassigned_alert_schedule',
                'ordering': ['site', 'send_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='siteunassignedalertschedule',
            constraint=models.UniqueConstraint(fields=('site', 'send_time'), name='unique_unassigned_schedule_per_site_time'),
        ),
    ]
