# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_siteunassignedalertschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitealertconfig',
            name='pending_send_at',
            field=models.DateTimeField(
                blank=True, null=True,
                help_text='Uso interno (debounce de HIGH_RISK_START): si tiene fecha futura, '
                          'ya hay un envio acumulado agendado y no hay que agendar otro.',
            ),
        ),
    ]
