# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_sitealertconfig_pending_send_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitealertconfig',
            name='alert_type',
            field=models.CharField(
                choices=[
                    ('HIGH_RISK_START', 'Inicio alto riesgo'),
                    ('ACTIVE_WITHOUT_SESSION', 'Activo sin sesion'),
                ],
                max_length=40,
            ),
        ),
    ]
