# Generated by Django 6.0.4 on 2026-04-29 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companymembership_sitemembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('resource_type', models.CharField(choices=[('PERSON', 'Persona'), ('MACHINERY', 'Maquinaria')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de recurso',
                'verbose_name_plural': 'Categorias de recurso',
                'db_table': 'resources_resource_category',
                'ordering': ['resource_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=40, null=True)),
                ('resource_type', models.CharField(choices=[('PERSON', 'Persona'), ('MACHINERY', 'Maquinaria'), ('BOTH', 'Ambos')], default='PERSON', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_titles', to='companies.company')),
            ],
            options={
                'verbose_name': 'Cargo laboral',
                'verbose_name_plural': 'Cargos laborales',
                'db_table': 'resources_job_title',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_uid', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('ARCHIVED', 'Archivado')], default='ACTIVE', max_length=20)),
                ('display_name', models.CharField(max_length=180)),
                ('normalized_name', models.CharField(blank=True, max_length=180)),
                ('person_rut', models.CharField(blank=True, max_length=20, null=True)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('internal_code', models.CharField(blank=True, max_length=60, null=True)),
                ('is_trackable', models.BooleanField(default=True)),
                ('last_partida_cod', models.CharField(blank=True, max_length=120, null=True)),
                ('last_partida_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_created', to=settings.AUTH_USER_MODEL)),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.jobtitle')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_updated', to=settings.AUTH_USER_MODEL)),
                ('resource_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resources.resourcecategory')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'db_table': 'resources_resource',
                'ordering': ['company', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceSiteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('PRIMARY', 'Principal'), ('LOAN', 'Prestamo'), ('TEMPORARY', 'Temporal')], default='PRIMARY', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('ENDED', 'Terminada'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_assignments', to='resources.resource')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_assignments', to='companies.site')),
            ],
            options={
                'verbose_name': 'Asignacion de recurso a obra',
                'verbose_name_plural': 'Asignaciones de recurso a obra',
                'db_table': 'resources_resource_site_assignment',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='jobtitle',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_job_title_per_company'),
        ),
        migrations.AddConstraint(
            model_name='resourcesiteassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('resource',), name='unique_active_assignment_per_resource'),
        ),
    ]
