# Generated by Django 6.0.4 on 2026-06-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_jobtitle_site'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobtitle',
            name='unique_job_title_per_company',
        ),
    ]
